sudo: required

stages:
  - test
  - deploy

language: bash

services:
  - docker

jobs:
  include:
    - stage: test
      before_install:
        - docker -v
      before_script:
        - docker-compose -v
      script:
        - echo "test 1"
        - echo "test 2"
      if: branch != master

    - stage: deploy
      before_install:
        - docker -v
      before_script:
        - docker-compose -v
      script:
        - echo "test 3"
        - echo "test 4"
      if: branch = master
      
